### ISSUE TITLE
Is it correct to call bash /dev/{tcp,udp}/ being part of the /dev/ subsytem

### ISSUE THREAD

**Issue by norpol** [trimstray/test-your-sysadmin-skills#3]
Hi, thank you for this document - it's joyful reading through it.
I wonder if this is the right question to ask:
> How to testing remote connection to port with dev subsystem?

Since I think it's not exactly part of "the" dev-filesystem, but more a feature built into some shell interpreters such as bash.

Maybe it's a good idea to rephrase the question a bit, for example into something like:
> "How can you do a TCP or UDP connection without netcat?"

**Comment by trimstray** [comment]
Hi!

Interesting suggestion, thanks. Do you know other methods of testing connections without using external tools like ping or netcat? Only using the mechanisms provided with GNU/Linux?

**Comment by trimstray** [comment]
Thanks for great suggestions and a help me better understand this mechanism.

I completely rewrite this question, like this:

`Developer reports a problem with connectivity to the remote service. Use /dev for troubleshooting.`
