### ISSUE TITLE
The browser does not check the OS DNS cache, router's DNS cache, or ISP's dns cache.

### ISSUE THREAD

**Issue by DevBrent** [trimstray/test-your-sysadmin-skills#4]
To the best of my understanding the browser has it's own DNS cache. When this cache fails, it simply asks the OS to resolve the domain. The OS resolver has it's own cache which *it* will check. If it fails this, it resorts to asking the OS configured DNS servers. The OS configured DNS servers will typically be configured by DHCP from the router where the DNS servers are likely to be the ISP's DNS servers configured by DHCP from the internet gateway to the router. In the event the router has it's own DNS servers, it may have it's own cache otherwise you should be directed straight to your ISP's DNS servers most typically as soon as the OS cache was found to be empty.

This is probably too verbose for an expected response but "it checks the router cache" followed by "it checks the ISP cache" is so ambiguous you may end up with interviewers who interpret the correct answer as wrong if they themselves are not well-versed.

**Comment by trimstray** [comment]
Thanks a lot, I updated answer for this.
