### ISSUE TITLE
update SPF 

### ISSUE THREAD

**Issue by sk3pp3r** [trimstray/test-your-sysadmin-skills#58]

**Comment by rawsGit** [comment]
What is an SPF record? An SPF record is a TXT record published on the domain starting with "v=spf1". It specifies a list of IP addresses where email messages are allowed to sent on behalf of that domain.

EXAMPLE-A: v=spf1 a mx ip4:127.0.0.1 a:myhostname -all

EXAMPLE-B:
v=spf1 include:_spf-a.microsoft.com include:_spf-b.microsoft.com include:_spf-c.microsoft.com include:_spf-ssg-a.msft.net include:spf-a.hotmail.com include:_spf1-meo.microsoft.com -all

For more, visit Dmarcly website and locate Tools.

**Comment by sk3pp3r** [comment]
.
